menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-31166339-5
analytics_site_name: topdna.org
rss: