menu:
  首页: /
  随感: /categories/essay/
  技术: /categories/tech/
  理财: /categories/investment/
  生活: /categories/life/
  归档: /archives

widgets: 
- search
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  weibo: true
  qzone: true
  google: true
  facebook: true
  twitter: true

fancybox: true

google_analytics: UA-31166339-5
analytics_site_name: topdna.org
rss: